server:
  port: 9898
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-microservice
            uri: lb://BOOK-MICROCERVICE
            predicates:
              - Path=/books/**
          - id: user-microservice
            uri: lb://USER-MICROCERVICE
            predicates:
              - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8008/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instances-id:${random.value}}